language: ruby
build_environment: ubuntu1304
env:
  global:
    - DB=psql
    - TRAVIS=true
  matrix:
    - TASK=spinach
    - TASK=spec
    - TASK=jasmine:ci
before_install:
  - sudo apt-get install libicu-dev -y
branches:
  only:
    - 'master'
services:
  - pgsql
rvm:
  - 2.0.0
before_script:
  - "cp config/database.yml.$DB config/database.yml"
  - "cp config/gitlab.yml.example config/gitlab.yml"
  - "bundle exec rake db:setup"
  - "bundle exec rake db:seed_fu"
script: "bundle exec rake $TASK --trace"
